{% set version = "0.22.0" %}
{% set python_min = "3.8" %}

package:
  name: movingpandas
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/m/movingpandas/movingpandas-{{ version }}.tar.gz
  sha256: 0866b3bd12da797e6221db6494c84b7b03fad7ca746919881a26c2a51c07fac8

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - geopandas-base
    - geopy
    - matplotlib-base
    - pyproj

test:
  requires:
    - python {{ python_min }}
  imports:
    - movingpandas

about:
  home: https://github.com/movingpandas/movingpandas
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'MovingPandas provides trajectory data structures and functions for handling movement data'

extra:
  recipe-maintainers:
    - raybellwaves
    - anitagraser
    - jorisvandenbossche
