{% set version = "0.14rc1" %}

package:
  name: movingpandas
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/movingpandas/movingpandas-{{ version }}.tar.gz
  sha256: 17e27b085c9971082aed21c1725cb8f79d5a099cdcca21563d75f0b7cd4abd82

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - fiona
    - geopandas-base
    - geopy
    - matplotlib-base
    - numpy
    - pandas
    - rtree
    - shapely

test:
  imports:
    - movingpandas

about:
  home: https://github.com/anitagraser/movingpandas
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: MovingPandas implements Trajectory classes and corresponding methods based on GeoPandas

extra:
  recipe-maintainers:
    - anitagraser
    - jorisvandenbossche
